version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "whatmovie-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-t3hxb5koo1so"
s3_prefix = "whatmovie-api"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

