AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  whatmovie-api

Globals:
  Function:
    Timeout: 3

Resources:

  MoviesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: MoviesApiAuthorizer
        AddDefaultAuthorizerToCorsPreflight: False
        Authorizers: 
          MoviesApiAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:eu-west-1:647974117295:userpool/eu-west-1_k4gGWwz9y

  GetMovies:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::647974117295:role/lambda-role
      CodeUri: movies/
      Handler: api/movies.get
      Runtime: nodejs12.x      
      Events:
        Movies:
          Type: Api
          Properties:
            RestApiId: !Ref MoviesApi
            Path: /movies
            Method: get
            RequestParameters:
              - method.request.querystring.currentPage
              - method.request.querystring.itemsPerPage
              - method.request.querystring.searchTerm
              - method.request.querystring.genre
  
  GetRatedMovies:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::647974117295:role/lambda-role
      CodeUri: movies/
      Handler: api/ratedMovies.get
      Runtime: nodejs12.x
      Events:
        Ratings:
          Type: Api
          Properties:
            RestApiId: !Ref MoviesApi
            Path: /movies/rated
            Method: get

  PutMovieRating:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::647974117295:role/lambda-role
      CodeUri: movies/
      Handler: api/rating.put
      Runtime: nodejs12.x
      Events:
        Ratings:
          Type: Api
          Properties:
            RestApiId: !Ref MoviesApi
            Path: /ratings
            Method: put

  PutWatchList:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::647974117295:role/lambda-role
      CodeUri: movies/
      Handler: api/myList.put
      Runtime: nodejs12.x
      Events:
        Ratings:
          Type: Api
          Properties:
            RestApiId: !Ref MoviesApi
            Path: /watchlist
            Method: put

  DeleteWatchList:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::647974117295:role/lambda-role
      CodeUri: movies/
      Handler: api/myList.delete
      Runtime: nodejs12.x
      Events:
        Ratings:
          Type: Api
          Properties:
            RestApiId: !Ref MoviesApi
            Path: /watchlist
            Method: delete
  
  GetWatchList:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::647974117295:role/lambda-role
      CodeUri: movies/
      Handler: api/myList.get
      Runtime: nodejs12.x
      Events:
        Ratings:
          Type: Api
          Properties:
            RestApiId: !Ref MoviesApi
            Path: /watchlist
            Method: get
            RequestParameters:
              - method.request.querystring.currentPage
              - method.request.querystring.itemsPerPage

  GetRecommendations:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::647974117295:role/lambda-role
      CodeUri: movies/
      Handler: api/recommendations.get
      Runtime: nodejs12.x
      Events:
        Recommendations:
          Type: Api
          Properties:
            RestApiId: !Ref MoviesApi
            Path: /recommendations
            Method: get
            RequestParameters:
              - method.request.querystring.currentPage
              - method.request.querystring.itemsPerPage

  GetPopularMovies:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::647974117295:role/lambda-role
      CodeUri: movies/
      Handler: api/popularMovies.get
      Runtime: nodejs12.x
      Events:
        Recommendations:
          Type: Api
          Properties:
            RestApiId: !Ref MoviesApi
            Path: /popularmovies
            Method: get
            RequestParameters:
              - method.request.querystring.currentPage
              - method.request.querystring.itemsPerPage

  GetMovie:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::647974117295:role/lambda-role
      CodeUri: movies/
      Handler: api/movies.getById
      Runtime: nodejs12.x
      Events:
        Movie:
          Type: Api
          Properties:
            RestApiId: !Ref MoviesApi
            Path: /movie
            Method: get
            RequestParameters:
              - method.request.querystring.movieId

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  Region:
    Description: "Region"
    Value: !Ref AWS::Region

  ApiId:
    Description: "API ID"
    Value: !Ref MoviesApi

  ApiUrl:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub 'https://${MoviesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
